name: hasura_connect
description: Connect your Flutter/Dart apps to Hasura simply. All the power of GraphQL and Postgres in Flutter
version: 1.2.1
homepage: https://github.com/Flutterando/hasura_connect

dependencies:
  websocket: ^0.0.5
  http: '>=0.12.0 <1.0.0'
  shared_preferences: '>=0.5.6 <1.0.0'
  path_provider: ^1.6.5
  hive: '>=1.0.0 <2.0.0'
  uuid: ^2.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.1.0 <3.0.0'
